### ISSUE TITLE
Documentation and some questions

### ISSUE THREAD

**Issue by dukex** [vulcand/vulcan#20]
Hi, I'm try use vulcan.

I read the README.md and I have some questions:

What routes the vulcan send to server control?

On my tests the vulcan call:  /auth and /

`/auth`  - with params like described here https://github.com/mailgun/vulcan#authorization
`/`  -  I believe here I need parser param url and create the json with tokens and upstreams

but on example https://github.com/mailgun/vulcan#control-server-example only /auth route is created, 

I lost some information on README?

What I need do to denied access? 

My /auth look like it: (I am using Sinatra to control server)

``` ruby
get '/auth' do
  content_type :json
  if user_logged?
    status 200
  else
    status 403
  end
end
```

Even when user_logged? is false and status is 403 vulcan keep passing request to my server 

Regards,
Duke

ps: I tried send a message a google groups but didn't work

**Comment by klizhentas** [comment]
Hi Duke!

Thanks for your interest with the project. Every request is sent to the url supplied when starting the service:

``` bash
       -c=http://localhost:5000    # control server url#1
```

That means that when request arrives Vulcan will request this url for instructions. 
You'd need to reply with tokens and upstreams right in the same response, so Vulcan would know what to do.

It also means that if you change control url to this:

``` bash
       -c=http://localhost:5000/my-control-url-goes-here   # control server url#1
```

Vulcan will query this url  (http://localhost:5000/my-control-url-goes-here) on every request from the client.

Let me know if you have any other questions,
Sasha

**Comment by dukex** [comment]
Hi Sasha, 
Thank you very much, I think your answer help me a lot.

About the authenticate, vulcan store the client or some like it? because I don't see every request call /auth

**Comment by klizhentas** [comment]
Duke, 

Nope, there's no caching at the moment. May be you don't see in the vulcan logs because they are dumped to fs periodically in batches, and not right after the request?

Thanks,
Sasha

**Comment by dukex** [comment]
Thanks Sasha! I will learning more about vulcan! 

ps: About google groups, What happen?

**Comment by klizhentas** [comment]
Duke,

Just a side note: Vulcan is under heavy development now, so beware when integrating that API is likely to change:
- E.g. we will add tight etcd integrations
- Control servers are going away, and will be replaced with javascript ability

So if you are using it in production, make sure you are ready to change your implementation

**Comment by dukex** [comment]
Nice!
I am not using on production yet, but it's the idea.

Thank you!
