### ISSUE TITLE
Limits on per-upstream connections

### ISSUE THREAD

**Issue by pquerna** [vulcand/vulcan#29]
- Per-upstream you should be able to say, this upstream can only do 5 requests per second, or N concurrent connections at a time.

**Comment by klizhentas** [comment]
@pquerna This is done here:

https://godoc.org/github.com/mailgun/vulcan/limit/connlimit

**Comment by klizhentas** [comment]
@pquerna 

Rate limits are here:

https://godoc.org/github.com/mailgun/vulcan/limit/tokenbucket
