### ISSUE TITLE
Autoscaling groups for discover backend

### ISSUE THREAD

**Issue by pquerna** [vulcand/vulcan#32]
- Hitting the Rackspace or Amazon API, find all members of an auto-scaling group, and add all active instances as responses to a discover() command.
- This will let more people use discover without having to buy into `etcd`

**Comment by klizhentas** [comment]
I think it's a great idea!

**Comment by pquerna** [comment]
Basic support is now in master for using Rackspace as a backend.

**Comment by klizhentas** [comment]
this should go to vulcan-service repo
