### ISSUE TITLE
Support for raw-TCP balancing

### ISSUE THREAD

**Issue by pquerna** [vulcand/vulcan#34]
- Support for listening to non-HTTP listeners.
- API changes to allow `connection` balancing rather than just `request` balancing.
- Support for streaming TCP connections to upstreams

**Comment by klizhentas** [comment]
Paul, can you please elaborate more on the specific use-cases you have in mind for this feature?

**Comment by pquerna** [comment]
@klizhentas Use cases include:
- Websocket proxying
- Agent Protocol Proxying (eg, [racker/virgo](https://github.com/racker/virgo) -- I think this use case is really about custom applications that are powered by two way communication.  SPDY or HTTP/2 once fully available could remove some of this with hanging GETs being cheap, but this is still a ways from being 'real'.

Websockets may want 'native' support someday, using the HTTP-hop-by-hop, however that would be a much more complicated implementation.

**Comment by klizhentas** [comment]
That's a good use case, however I'd suggest to focus on the following first and make it the first iteration:
- Config file format finalisation (I'm currently working on it, will submit the format in 1-2 days)
- Make http(s) support awesome
- Structured logs as you've suggested
- Metrics - add custom metrics support and polish the ones that you've implemented
- Better integration with etcd (support for graceful adding/removing of upstreams)
- Failover  & failure detection
- Load balancing (support load balancing groups, weighted load balancing, coordination with failure detection)
- Rate limiting (almost done)

Once we are done with this we can move on to the other items mentioned buy you

Thanks,
Sasha

**Comment by klizhentas** [comment]
I'd just focus on writing programmatic http reverse proxy lib at the moment, otherwise it's getting too complicated
