### ISSUE TITLE
Add way to build 3rd Party Vulcan Modules

### ISSUE THREAD

**Issue by pquerna** [vulcand/vulcan#42]
## Background
- A common feature of web servers and reverse proxies is to allow 3rd parties to extend their capabilities with custom code.
- This is difficult generally in Go, because there is no dynamic linking / `dlopen`.
## Proposal

Users would create a `main.go`, and run `go build` to produce a single binary containing Vulcan and their custom modules.

Because of how Go works, Vulcan would be a library that users would import.  An example, if I made two Vulcan Modules aka "vmod"s, one to implement PageSpeed compressions and another to store rate limiting data in Postgres,  and wanted to enable them in my own build, I would make a very simple `main.go`, that imported each, and passed them to  `vulcan.service.RunWithModules`:

``` go
package main

import (
    "github.com/mailgun/vulcan/service"
    "github.com/pquerna/vmod-pagespeed"
    "github.com/pquerna/vmod-postgres-ratelimit"
)

func main() {
    modules := []service.Vmod{
        vmod_pagespeed,
        vmod_postgres_ratelimit}
    service.RunWithModules(modules)
}

```

These modules would each have an interface that exposes middlewares to the Javascript API documented in #25.  They could also register themselves to handle command line args, or to  run at hooks during request processing.

The modules would implement something like the following interface:

``` go
type RegisterFunc func(s *vulcan.Service) error

type Vmod interface {
    RegisterFunc
}
```

`vulcan.Service` would be extended to have many more methods like `AddMiddleware`, `AddCommand`, `AddRequestTransformer`, `AddLogger` etc, which would each take a callback function.

**Comment by philips** [comment]
Why not just accept everything into the repo like the Linux Kernel and just don't enable anything unless a command line flag for each is added? It is very nice that things like openresty just compile all of the nginx modules together.

**Comment by russellhaering** [comment]
I propose:
1. Drop the Javascript support entirely
2. Move all the middleware instantiation and registration to Go
3. Optionally, build a utility that takes a config file (let people put in arbitrary "go get" urls, along with any parameters to the module) and generates buildable project, complete with a main.go from it.

**Comment by songgao** [comment]
Here's an idea that just pop into my head:

The purpose of the idea is to enable third party modules to be built into Vulcan binary, but avoid giant binary that consists of all unnecessary parts. A secondary goal would be allowing each third party module to be in a  separate repo.
1. Create a directory (a Go package) in Vulcan, for describing third party module uses. Let's call the dir/package `modules`.
2. All third party modules, apparently, should implement a certain initializer and a series handlers, in other words, it implements an interface, say `Mod`. Then each module can provide a constructor that returns a `*Mod`.
3. In `modules` package, there's an important `map[string] func(interface{}) *Mod`. It maps module names to their constructors. When Vulcan service starts, it looks in this `map` for all modules to load.
4. Each module would provide a file that consists an `init()` function, which adds itself to the `map` mentioned in 3. The `init()` functions are executed at very beginning so by the time modules are being loaded, module constructors are already in the `map`. This file is in `modules` directory.
5. By default, the `modules` does not contain any module files mentioned in 4. Users can download such files into `modules`, and rebuild Vulcan to add modules.

This way, although the binary is still statically linked, it's more flexible and wouldn't give user a bunch of unnecessary parts.

EDIT: typo in last paragraph; names

**Comment by andrebq** [comment]
At this moment something like dynamic-loading of modules can be done using some kind of IPC (http.ReverseProxy is one option).

This don't give access to the memory of the main process out-of-the-box (I consider this a good thing) but could be implemented using something like mmap.

Then the main process can be configured to map some urls to some modules.

**Comment by zwoop** [comment]
Hmmmm, it seems some sort of content adaptation interface could be appropriate. Such as, ICAP (http://www.rfc-editor.org/rfc/rfc3507.txt). And then provide a framework for people to implement ICAP services which Vulcan can use.

**Comment by klizhentas** [comment]
@russellhaering approach won - this package will be a library that provides stable loadbalancing and forwarding functionality. There should be another repo that uses this library.
