### ISSUE TITLE
Extract and extend the rate limiting and load balancing routines

### ISSUE THREAD

**Issue by wolfeidau** [vulcand/vulcan#45]
I am keen to use or build both these "modules" for a proxy I am building for MQTT.

Would be keen to know what you thought of this?

Aim would be to decouple them from your backends, while still supporting the interface they provide and adding more metrics about the operation of these "modules" for want of a better word.

Cheers

**Comment by pquerna** [comment]
CC: @klizhentas

**Comment by pquerna** [comment]
I'm good with PRs that build stronger interfaces between parts of Vulcan.

I'm unsure about saying that module X will have interface Y forever though, I think we still would like some flexibility in changing the interfaces until Vulcan is more stabilized.  Maybe a proposal first of what the `interface` would look like?

**Comment by wolfeidau** [comment]
Yeah totally understand, more just sounding you out on this idea as:
- They look like a good starting point
- There isn't much around in golang at the moment

Of these have an important role in your service so I would just be borrowing them and need to ensure I follow any changes.

I will have a hack around and see if I can come up with some way of doing this cleanly.   

Thanks.

**Comment by klizhentas** [comment]
I've replaced everything in this repo with just a core functionality with interfaces, so you can implement a load balancing algo and plug it in. Rate limiting can be implemented via callback interface now

**Comment by wolfeidau** [comment]
That is great I managed to get together a backend for Redis which is working well, loving the interfaces makes implementing my own very nice. Was planning on pushing this up in a PR once I get a bit more testing done.

https://github.com/wolfeidau/rifter/tree/master/backend

I was grappling with some of the other pieces over the weekend then got side tracked on MQTT related things.

Thanks a lot I look forward to getting more of this integrated, big fan of not reinventing such nice wheels.

Thanks again.

**Comment by klizhentas** [comment]
@wolfeidau  @pquerna This is done and documented here:

http://mailgun.github.io/vulcan-docs/

**Comment by wolfeidau** [comment]
This is amazing digging into it now.

Thanks for all the work you have done @klizhentas much appreciated!
