### ISSUE TITLE
Middleware not able to modify http.Request as expected

### ISSUE THREAD

**Issue by davidbirdsong** [vulcand/vulcan#51]
Again, this is specific to `httploc.HttpLocation`, and I'm a little uncertain of what gets copied in a [struct copy](https://github.com/mailgun/vulcan/blob/master/location/httploc/httploc.go#L176). 

Based on trial and error, the headers I add in my `Middleware.ProcessRequest` are lost and not in the outbound http.Request that my upstream host sees. This line shows [req](https://github.com/mailgun/vulcan/blob/master/location/httploc/httploc.go#L157) is passed into Middleware, but only [httpReq](https://github.com/mailgun/vulcan/blob/master/location/httploc/httploc.go#L168) is sent to RoundTrip.

I'm happy to supply patches, but I'm not actually sure what a good fix is. It mostly depends on the expectation of projects linking to vulcan.

I could also supply my own Location implementation, but I thought I'd bring this up since Middlewares are supposed to be able to change http.Request and not just the http.Request.URL according to the docs.

**Comment by klizhentas** [comment]
I would add a `Transparent` flag to the options:

https://github.com/mailgun/vulcan/blob/master/location/httploc/httploc.go#L39

In this case I would turned rewriting off at all here

https://github.com/mailgun/vulcan/blob/master/location/httploc/httploc.go#L113

```
if !options.Transparent {
    rewrite
}
```

**Comment by davidbirdsong** [comment]
Yeah, this sounds good.
