### ISSUE TITLE
Configurable Transport MaxIdleConnsPerHost

### ISSUE THREAD

**Issue by manell** [vulcand/vulcan#58]
This question is specific to httploc.HttpLocation. [src](https://github.com/mailgun/vulcan/blob/master/location/httploc/httploc.go#L78)

Maybe I did something wrong but I was doing some benchmarking with multiples connections and I was noticed that only 2 TCP connections were re-used between the proxy server and the final endpoint [net/http](http://golang.org/src/pkg/net/http/transport.go#L44). It could be possible to add some options parameter for set the MaxIdleConnsPerHost variable?

**Comment by klizhentas** [comment]
Interesting. Can you share the benchmark/measure details so I can reproduce?

**Comment by klizhentas** [comment]
@manell you can now supply these parameters via 
https://github.com/mailgun/vulcan/blob/master/location/httploc/httploc.go#L51

**Comment by klizhentas** [comment]
@manell Let me know if you'd need anything else. Meanwhile, I'm closing the issue
