### ISSUE TITLE
Incorrect usage of log.err

### ISSUE THREAD

**Issue by dreid** [vulcand/vulcan#8]
[log.err](https://twistedmatrix.com/documents/current/api/twisted.python.log.err.html) takes 2 arguments, `_stuff`, and `_why` these arguments are both poorly named and under-documented.  The first argument (`_stuff`) is expected to be `None`, an `Exception`, or a `Failure` object. 

The second argument (`_why`) is a string describing the first argument.

Two incorrect usages exist in the code base:
1. `log.err` with string first argument.
2. `log.err` with with no arguments immediately following `log.err` with string first argument.

In both cases the better construction would be a single `log.err` of the form:

``` python
log.err(None, "String error message")
```

Or if you prefer to be explicit about the creation of the `Failure` object

``` python
log.err(Failure(), "String error message")
```

In some cases it appears that you are using an existing failure instance (often called `reason`) and passing a string so you can format the error message and the traceback into the string.  In which case it'd still be better to use either of the above constructions and either fix [twisted#6424](https://tm.tl/6424) or do your own message formatting in a log observer.

**Comment by klizhentas** [comment]
This issue was fixed by #11
